# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiss" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "2ec85d15b08bf645f7ede33e62a349c849b425f5f56093a5d668fff6291d3d33"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f98cc6068913cf7e2406526bea08ca82eb922db33d3bf73c4e08e81ef2bcbbfa"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8f94e01cb3589f53ea7d13bb387a9d559b5e02cdecdfc1f8b95ee6bf95839dfe"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec5479a12f4fdb358099ad41c9122207963a24868a26b15e85994d484baa9190"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aiss"
  desc "Fuzzy picker over AI CLI session histories (Claude Code / Codex / Copilot / Gemini)"
  homepage "https://github.com/jarvan1/aiss"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiss"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiss"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To enable the Ctrl-X Ctrl-W key binding, add one line to your shell rc:
      eval "$(aiss init zsh)"     # or: aiss init bash | aiss init fish
    On Windows (PowerShell), add to your $PROFILE instead:
      Invoke-Expression (& aiss init powershell | Out-String)
  EOS
end
