# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiss" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "28acfcc2ee3a365aa20d698a549f020a8a4806c06b276a65238408eced38b786"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e40a866c383a2c50ee29007afe275201a97b7121014aa7d0973bba538b5f1ed"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "78886ac19df2ff2c016b450a5d63a6d30821f2fb223918cd5fa3ccfcbed66e36"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "467c4827ab474aeb2e1e2b0f2d8ec3628a1f35734eaa9208d01f61777236be8d"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aiss"
  desc "Fuzzy picker over AI CLI session histories (Claude Code / Codex / Copilot / Gemini)"
  homepage "https://github.com/jarvan1/aiss"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiss"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiss"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To enable the Ctrl-X Ctrl-W key binding, add one line to your shell rc:
      eval "$(aiss init zsh)"     # or: aiss init bash | aiss init fish
    On Windows (PowerShell), add to your $PROFILE instead:
      Invoke-Expression (& aiss init powershell | Out-String)
  EOS
end
