# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiss" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7fec4fd8a23aa385755ac24c01534be5e0295f1eb0bc1c706acbd26c0e6a5640"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe5d38b27102684c8dc58cda2613ed7cf1c467d55dda52e1c2f5d8319ced8e2c"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "253b853a3c4bd4da7d2b5244249121b623f0ada2d8bc7dddaa7ba30b584f33da"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "60693be2ba1f606a3c3d8e5362bdde7ce50fe2a19cf31f94a842bcd41025c291"
      url "https://github.com/jarvan1/aiss/releases/download/v#{version}/aiss_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aiss"
  desc "Fuzzy picker over AI CLI session histories (Claude Code / Codex / Copilot / Gemini)"
  homepage "https://github.com/jarvan1/aiss"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiss"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aiss"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To enable the Ctrl-X Ctrl-W key binding, add one line to your shell rc:
      eval "$(aiss init zsh)"     # or: aiss init bash | aiss init fish
  EOS
end
